//
//  ShowArticleInteractor.swift
//  NewsCap
//
//  Created by Chris on 14/05/2020.
//  Copyright (c) 2020 Chris78. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowArticleBusinessLogic {
    func getArticle(request: ShowArticle.GetArticle.Request)
}

protocol ShowArticleDataStore {
    var article: Article! { get set }
}

class ShowArticleInteractor: ShowArticleBusinessLogic, ShowArticleDataStore {
    var article: Article!

    var presenter: ShowArticlePresentationLogic?
    var worker: ShowArticleWorker?
    var articlesWorker = ArticlesWorker()

    // MARK: Get Article

    func getArticle(request: ShowArticle.GetArticle.Request) {
        let response = ShowArticle.GetArticle.Response(article: article)
        presenter?.presentArticle(response: response)
    }
}
