//
//  ListArticleModels.swift
//  ListArticleCap
//
//  Created by Chris on 13/05/2020.
//  Copyright (c) 2020 Chris78. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListArticle {
    // MARK: Use cases

    enum Fetch {
        struct Request {
            var filter: String?
        }
        struct Response {
            var articles: [Article]?
            var errorMessage: String?
        }
        struct ViewModel {
            struct DisplayArticle {
                var imageUrl: String
                var title: String
                var description: String
            }
            var displayArticles: [DisplayArticle]
            struct Error {
                var errorMessage: String?
            }
        }
    }
}
