//
//  ListArticleInteractor.swift
//  ListArticleCap
//
//  Created by Chris on 13/05/2020.
//  Copyright (c) 2020 Chris78. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListArticleBusinessLogic
{
    func fetchListArticle(request: ListArticle.Fetch.Request)
    func fetchListArticleImage(request: ListArticle.FetchImage.Request)
}

protocol ListArticleDataStore
{
    //var name: String { get set }
    var articles: [Article]? { get }
}

class ListArticleInteractor: ListArticleBusinessLogic, ListArticleDataStore
{
    var articles: [Article]?
    
    var presenter: ListArticlePresentationLogic?
    var worker: ListArticleWorker?
    var articlesWorker = ArticlesWorker()
    //var name: String = ""
    
    // MARK: Do something
    
    func fetchListArticle(request: ListArticle.Fetch.Request)
    {
        worker = ListArticleWorker()
        
        articlesWorker.fetch(success: { response in
            self.articles = response.articles
            let resp = ListArticle.Fetch.Response(articles: response.articles, isError: response.isError, message: response.message)
            self.presenter?.presentFetchListArticle(response: resp)
        }, fail: { error in
            let resp = ListArticle.Fetch.Response(articles: [], isError: error.isError, message: error.message)
            self.presenter?.presentFetchListArticle(response: resp)
        })
    }
    
    func fetchListArticleImage(request: ListArticle.FetchImage.Request)
    {
        worker = ListArticleWorker()
        articlesWorker.fetchImage(request: request, success: { response in
            let resp = ListArticle.FetchImage.Response(imageUrl: response.imageUrl, image: response.image, isError: response.isError)
            self.presenter?.presentFetchListArticleImage(response: resp)
        }, fail: { error in
            let resp = ListArticle.FetchImage.Response(isError: error.isError, message: error.message)
            self.presenter?.presentFetchListArticleImage(response: resp)
        })
    }
}
